# Generated by Django 5.0.6 on 2024-08-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like_liked_alter_like_post_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='network.post'),
        ),
    ]
